### PR TITLE
More specific LB error messages

### LINKED ISSUE #627: Better error messaging when a load balancer is deemed unsuitable
I uploaded an ssl-cert yesterday but was missing the intermediate certificate, when I got an error about that I went straight to the load balancer and updated to a previous cert I had uploaded.

Today I was getting:

```
$ emp set foo=bar -a services
error: currently assigned load balancer is not suitable for the given exposure
```

which makes sense after reading through `lbOk` with it failing on this section

```	
if p.SSLCert != lb.SSLCert {
    return false
}
```

instead of each of these sections returning "false", they should be returning a more descriptive error.

### PR DESCRIPTION
**Pull request by phobologic**
Fixes #627

### CODE REVIEW

**Comment by ejholmes** [comment]
:+1:

**Comment by mhahn** [comment]
:+1: thanks!

File: pkg/service/lb.go [hunk 1]
```diff
@@ -106,23 +106,57 @@ func lbTags(app string, process string) map[string]string {
 	}
 }
 
+type loadBalancerExposureError struct {
```
Comment (ejholmes) [inline pkg/service/lb.go]: Prefixing these with `loadBalancer` feels a little verbose since we're already in package lb. How about just `ExposureError` (exported so consumers can type assert on it). e.g.

```go
if err, ok := err.(*lb.ExposureError); ok {
        // Stuff
}
```

Comment (ejholmes) [inline pkg/service/lb.go]: I take that back, we're not in package lb. `LoadBalancerExposureError` would be fine imo.

**Comment by bmarini** [comment]
:+1:

**Comment by ejholmes** [comment]
:+1:
